name: Android
on: [push]
jobs:
  build:
    name: Build FCL Mesa Plugin Bridge
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          $ANDROID_NDK_HOME/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Bridge
          path: libs/*

